### ISSUE TITLE
Why is #define YAW_DIRECTION defined as -1

### ISSUE THREAD

**Issue by cagdask** [architbubber/MultiWii-Nrf24l01-SingleBoard#2]
Hi Any particular reason why #define YAW_DIRECTION -1 is defined? It took me a while to figure out this was causing a constant yaw motion in take off. I had to compare the original multiwii code and yours. I believe this might be specific to your board rotation but not directly related to GY87 sensor or NRF24L01

**Comment by architbubber** [comment]
You should read the comments in the code to understand it . I have clearly mentioned about this in comments
`/* NEW: not used anymore for servo coptertypes  <== NEEDS FIXING - MOVE TO WIKI */
    //#define YAW_DIRECTION 1
    #define YAW_DIRECTION -1 // if you want to reverse the yaw correction direction
    //#define YAW_DIRECTION 0 //if yaw aligned custom trial may ruin your copter`
It was used by me for my custom board, you'll have to check for yours and then uncomment the desired.
