### ISSUE TITLE
Wiring of transmitter

### ISSUE THREAD

**Issue by ArshaanTech** [architbubber/MultiWii-Nrf24l01-SingleBoard#4]
Can you give wiring for the transmitter part?

**Comment by architbubber** [comment]
Hi Arshaan,
Sorry for the delayed response, I have been a little busy. The wiring is as below

Throttle ---> AnalogPin 4
Yaw ---> AnalogPin 3
Pitch ---> AnalogPin 2
Roll ---> AnalogPin 1
AUX1 ---> AnalogPin 5
AUX2 ---> AnalogPin 0

For NRF the default wiring is there.
CE ---> Digital Pin 9
CSN ---> Digital Pin 10
MISO ---> Digital Pin 12
MOSI ---> Digital Pin 11
SCK ---> Digital Pin 13

I'll upload some diagrams for the same soon.
Till then Happy Flying !
